export { default as Footer } from './Footer'
export { default as Greetings } from './Greetings'
export { default as Loader } from './Loader'
export { default as NavBar } from './NavBar'
export { default as Services } from './Services'
export { default as Transactions } from './Transactions'